# Generated by Django 4.1.3 on 2023-07-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_entrega_url_alter_entrega_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='entrega/documento'),
        ),
    ]
