# Generated by Django 4.1.3 on 2023-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_entrega_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='calificacion',
            field=models.CharField(choices=[('en revision', 'en revision'), ('aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='en revision', max_length=20),
        ),
    ]
